SFUGS\UGS1Bundle\Entity\Location:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    events:
      targetEntity: SFUGS\UGS1Bundle\Entity\Event
      mappedBy: location
